<a href="https://colab.research.google.com/github/aiyaarie/CSST101-Laboratory/blob/main/LabPractical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

My First R Program

1. Print

In [ ]:
print("I love R programming")
cat("R", "Programming")

[1] "I love R programming"
R Programming

2. Variables and Data Types

In [ ]:
myString <- "I love R Programming"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE


print(myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I love R Programming"

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [1]:
x <- 10
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y
mod <- x %% y
exp <- x ^ y

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 1000

4. User Input

In [ ]:
name <- readline("Enter Name: ")
cat("Welcome to R Programming: ", name)

Enter Name: Althea
Welcome to R Programming:  Althea

5. Decision Making

In [ ]:
grade <- 90
if (grade < 75){
print("Failed")
} else {print("Passed")
}

[1] "Passed"

6. Loop

In [2]:
for (i in 1:6){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6

7. Function

In [3]:
addNumber <- function(a,b){
  return(a+b)
}

addNumber(3,7)

[1] 10

8. Vectors

In [4]:
grades <- c(90,80,98,97,95)

grades

cat("MEAN: ", mean(grades))
cat("\nMAX: ",max(grades))
cat("\nMIN: ",min(grades))
cat("\nLENGTH: ",length(grades))
cat("\nMEDIAN: ",median(grades))
summary(grades)

[1] 90 80 98 97 95

MEAN:  92
MAX:  98
MIN:  80
LENGTH:  5
MEDIAN:  95

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
     80      90      95      92      97      98

9. Matrices

In [5]:
A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [6]:
students <- list(
  Name = "Althea" ,
  Course = "BSCS" ,
  Grade = 100
)

students

$Name
[1] "Althea"

$Course
[1] "BSCS"

$Grade
[1] 100

11. Dataframe

In [8]:
students <- data.frame(
  name = c("Althea", "Marie", "Palentinos"),
  course = c("BSCS", "BSIT", "BSBA"),
  grade = c(90, 99, 95)

)

students

  name       course grade
1 Althea     BSCS   90
2 Marie      BSIT   99
3 Palentinos BSBA   95

12. Write to CSV

In [9]:
write.csv(students, "student.csv")

13. Read CSV File

In [10]:
data <-read.csv("student.csv")

head(data)
summary(data)

  X name       course grade
1 1 Althea     BSCS   90
2 2 Marie      BSIT   99
3 3 Palentinos BSBA   95

       X              name          course      grade
 Min.   :1.0   Length   : 3   Length   :3   Min.   :90.00
 1st Qu.:1.5   N.unique : 3   N.unique :3   1st Qu.:92.50
 Median :2.0   N.blank  : 0   N.blank  :0   Median :95.00
 Mean   :2.0   Min.nchar: 5   Min.nchar:4   Mean   :94.67
 3rd Qu.:2.5   Max.nchar:10   Max.nchar:4   3rd Qu.:97.00
 Max.   :3.0                                Max.   :99.00